version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello-app-deploy-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-19mljn8tdoqcs"
s3_prefix = "hello-app-deploy-stack"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
